// Avatares musicais para seleção de nickname
export const nicknameAvatars = [
  { emoji: '🎸', label: 'Guitarrista' },
  { emoji: '🎤', label: 'Cantor(a)' },
  { emoji: '🥁', label: 'Baterista' },
  { emoji: '🎹', label: 'Tecladista' },
  { emoji: '🎷', label: 'Saxofonista' },
  { emoji: '🎺', label: 'Trompetista' },
  { emoji: '🪗', label: 'Acordeonista' },
  { emoji: '🪕', label: 'Banjo' },
  { emoji: '🎻', label: 'Violinista' },
  { emoji: '🪘', label: 'Percussionista' },
  { emoji: '🎼', label: 'Maestro(a)' },
  { emoji: '🎧', label: 'DJ' },
  { emoji: '📻', label: 'Rádio' },
  { emoji: '🎵', label: 'Nota Musical' },
  { emoji: '🎶', label: 'Notas Musicais' },
  { emoji: '🪇', label: 'Maracas' },
  { emoji: '🪈', label: 'Clarinete' },
  { emoji: '🎚️', label: 'Mixador' },
  { emoji: '🎙️', label: 'Microfone' },
  { emoji: '🪕', label: 'Banjo' },
  { emoji: '🎛️', label: 'Mesa de Som' },
  { emoji: '🎬', label: 'Clap de Estúdio' },
  { emoji: '🎤', label: 'Vocalista' },
  { emoji: '🎷', label: 'Sax' },
  { emoji: '🎺', label: 'Trompete' },
  { emoji: '🎻', label: 'Violino' },
];
